name: Select Runner
on: 
  workflow_dispatch:
    inputs:
      # default는 ubuntu
      # select 박스를 만들어서 선택하게끔 설정
      os:
        description: 'Runner OS'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - 'ubuntu-latest'
        - 'windows-latest'
        - 'macos-latest'
jobs:
  build:
    name: Build
    runs-on: ${{ github.event.inputs.os }}
    steps:
    - id: checkout
      name: Checkout 
      uses: actions/checkout@v2
    - id: run
      name: Run
      run: |
        echo "OS: ${{ github.event.inputs.os}}"
        echo "Hello World"
