name: Workflow Run
on: 
  workflow_run:
     # Trigger with Tags 워크플로우가 실행이 completed 라면 실행
    workflows: ["Trigger with Tags"]
    types:
    - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Chec행out 
      uses: actions/checkout@v2
    - name: Build project
      run: |
        echo "Build Project"
    - name: Run tests
      run: |
        echo "Run Test"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to production
      run: |
        echo "Deploying to production server"
